# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class Test:
    def __init__(self):
        self.vars = {}
        self.driver = webdriver.Chrome()

    def setup_method(self, method):
        pass

    def teardown_method(self, method):
        self.driver.quit()

    def test_(self):
        self.driver.get('http://test1.caichufang.com:7060/admin/login.html')
        self.driver.set_window_size(765, 691)
        # self.driver.find_element(By.ID, "userName").click()
        # self.driver.find_element(By.ID, "userName").click()
        # self.driver.find_element(By.ID, "userName").send_keys("caichufang")
        # self.driver.find_element(By.ID, "userPwd").send_keys("admin123")
        # self.driver.find_element(By.ID, "loginCaptcha").send_keys("9651")
        # self.driver.find_element(By.ID, "loginCaptcha").send_keys(Keys.ENTER)
        self.driver.add_cookie({'name': 'SESSION', 'value': '859b82d1-beda-4f87-87c0-16879d98f3b8'})
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".product-nav-bar:nth-child(1) li:nth-child(1) .nav-nav-title").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT, "创建新商品").click()
        self.driver.find_element(By.ID, "product_classify").click()
        dropdown = self.driver.find_element(By.ID, "product_classify")
        dropdown.find_element(By.XPATH, "//option[. = '非处方药']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#product_classify > option:nth-child(2)").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.ID, "classTow").click()
        dropdown = self.driver.find_element(By.ID, "classTow")
        dropdown.find_element(By.XPATH, "//option[. = '保健食品']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#classTow > option:nth-child(3)").click()
        self.driver.find_element(By.ID, "product_name").click()
        self.driver.find_element(By.ID, "product_name").send_keys("脑络通")
        self.driver.find_element(By.ID, "generic_name").send_keys("胶囊")
        self.driver.find_element(By.CSS_SELECTOR,
                                 "#select2-myManufacturer-container > .select2-selection__placeholder").click()
        self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").click()
        self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys("北京")
        self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "product_Specifications").click()
        self.driver.find_element(By.ID, "product_Specifications").send_keys("1g*1盒")
        self.driver.find_element(By.ID, "approval_number").send_keys("国药准字")
        self.driver.find_element(By.ID, "product_barcode").send_keys("154561564451")
        self.driver.find_element(By.ID, "product_Company").click()
        dropdown = self.driver.find_element(By.ID, "product_Company")
        dropdown.find_element(By.XPATH, "//option[. = '合']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#product_Company > option:nth-child(7)").click()
        self.driver.find_element(By.NAME, "button").click()
        self.driver.find_element(By.LINK_TEXT, "编辑").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.close()


if __name__ == '__main__':
    test = Test()
    test.test_()
